version: '3.8'
services:
  content-service:
    image: all-content-service:latest
    container_name: content-service
    ports:
      - "3008:3008"
    restart: always
    networks:
      - all-learner-ai-services-ai-network
networks:
  all-learner-ai-services-ai-network:
    driver: bridge
