version: '3.8'
services:
  content-service:
    build: . # <-- This tells Docker Compose to BUILD from the current directory
    container_name: content-service
    ports:
      - "3008:3008"
    restart: always
    env_file:
      - .env
    networks:
      - all-learner-ai-services-ai-network
networks:
  all-learner-ai-services-ai-network:
    driver: bridge
