name: Deploy or Rollback All-Content-Service

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - rollback
      environment:
        description: 'Target environment'
        required: true
        default: 'tn-staging'
        type: choice
        options:
          - tn-staging
      branch:
        description: 'Branch to deploy (only for deploy)'
        required: false
        default: 'lais-v2.0'
      rollback_tag:
        description: 'Tag to rollback to (only for rollback)'
        required: false

jobs:
  deploy-or-rollback:
    runs-on: ubuntu-latest
    environment: tn-staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.ALL_SERVER_SSH_KEY }}" > key_target.pem
          chmod 600 key_target.pem

          echo "${{ secrets.ALL_SERVER_SSH_KEY }}" > key_jump.pem
          chmod 600 key_jump.pem

          echo "host=${{ secrets.TN_STAGING_HOST }}" >> "$GITHUB_ENV"
          echo "jump_host=${{ secrets.JUMPHOST }}" >> "$GITHUB_ENV"
          echo "target_dir=/home/all-staging-user/all-services/all-content-deploy" >> "$GITHUB_ENV"

      - name: Execute ${{ github.event.inputs.action }}
        run: |
          ACTION="${{ github.event.inputs.action }}"
          HOST="${{ env.host }}"
          JUMP_HOST="${{ env.jump_host }}"
          TARGET_DIR="${{ env.target_dir }}"
          BRANCH="${{ github.event.inputs.branch }}"
          ROLLBACK_TAG="${{ github.event.inputs.rollback_tag }}"

          SSH_COMMAND="ssh -o StrictHostKeyChecking=no -i key_jump.pem -J $JUMP_HOST -i key_target.pem $HOST"

          if [[ "$ACTION" == "deploy" ]]; then
            echo "Deploying branch $BRANCH to $HOST"
            $SSH_COMMAND << EOF
              echo "Navigating to $TARGET_DIR"
              cd "$TARGET_DIR" || { echo "Error: Directory $TARGET_DIR not found."; exit 1; }
              echo "Fetching all latest changes..."
              git fetch --all
              echo "Checking out $BRANCH..."
              git checkout "$BRANCH" || { echo "Error: Failed to checkout branch $BRANCH."; exit 1; }
              echo "Pulling latest changes for $BRANCH..."
              git pull origin "$BRANCH" || { echo "Error: Pull failed for branch $BRANCH."; exit 1; }
              echo "Stopping existing Docker containers..."
              docker-compose down || echo "No running containers to stop."
              echo "Building and starting new Docker containers..."
              docker-compose up -d --build || { echo "Docker compose failed."; exit 1; }
              echo "Cleaning dangling Docker images..."
              docker images --no-trunc -aqf "dangling=true" | xargs -r docker rmi || echo "No dangling images to remove."
              echo "Deployment complete for $BRANCH."
EOF

          elif [[ "$ACTION" == "rollback" ]]; then
            if [[ -z "$ROLLBACK_TAG" ]]; then
              echo "::error::Rollback tag is required"
              exit 1
            fi

            echo "Rolling back to tag $ROLLBACK_TAG on $HOST"
            $SSH_COMMAND << EOF
              echo "Navigating to $TARGET_DIR"
              cd "$TARGET_DIR" || { echo "Error: Directory $TARGET_DIR not found."; exit 1; }
              echo "Fetching tags..."
              git fetch --all --tags
              echo "Checking out tag $ROLLBACK_TAG..."
              git checkout "tags/$ROLLBACK_TAG" || { echo "Error: Failed to checkout tag $ROLLBACK_TAG."; exit 1; }
              echo "Stopping current Docker containers..."
              docker-compose down || echo "No running containers to stop."
              echo "Building and starting Docker containers from tag $ROLLBACK_TAG..."
              docker-compose up -d --build || { echo "Docker compose failed."; exit 1; }
              echo "Cleaning dangling Docker images..."
              docker images --no-trunc -aqf "dangling=true" | xargs -r docker rmi || echo "No dangling images to remove."
              echo "Rollback to $ROLLBACK_TAG complete."
EOF

          else
            echo "::error::Invalid action: $ACTION"
            exit 1
          fi
