name: Deploy or Rollback All-Content-Service

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - rollback
      environment:
        description: 'Target environment'
        required: true
        default: 'tn-staging'
        type: choice
        options:
          - tn-staging
      branch:
        description: 'Branch to deploy (only for "deploy" action)'
        required: false
        default: 'lais-v2.0'
      rollback_tag:
        description: 'Tag to rollback to (only for "rollback" action, e.g., deploy-tn-staging-v1.0.0)'
        required: false

jobs:
  deploy-or-rollback:
    runs-on: ubuntu-latest
    environment: tn-staging

    steps:
    - name: Checkout (for internal use, not needed on server)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.inputs.branch || 'lais-v2.0' }}

    - name: Set SSH Key and Target Host
      run: |
        echo "${{ secrets.SSH_KEY }}" > key.pem
        echo "${{ secrets.SSH_KEY }}" > jump_key.pem
        chmod 600 key.pem jump_key.pem
        echo "host=${{ secrets.TN_STAGING_HOST }}" >> "$GITHUB_ENV"
        echo "target_dir=/home/all-staging-user/all-services/all-content-deploy" >> "$GITHUB_ENV"
        echo "jump_host=${{ secrets.JUMPHOST }}" >> "$GITHUB_ENV"

    - name: Perform Deploy or Rollback
      run: |
        ACTION="${{ github.event.inputs.action }}"
        HOST="${{ env.host }}"
        TARGET_DIR="${{ env.target_dir }}"
        JUMP_HOST="${{ env.jump_host }}"
        SSH_COMMAND="ssh -o StrictHostKeyChecking=no -i jump_key.pem -J $JUMP_HOST -i key.pem $HOST"

        if [[ "$ACTION" == "deploy" ]]; then
          BRANCH="${{ github.event.inputs.branch }}"
          echo "Initiating deployment on $HOST from branch: $BRANCH"
          $SSH_COMMAND "cd $TARGET_DIR && ./deploy.sh $TARGET_DIR $BRANCH deploy"
        elif [[ "$ACTION" == "rollback" ]]; then
          ROLLBACK_TAG="${{ github.event.inputs.rollback_tag }}"
          if [[ -z "$ROLLBACK_TAG" ]]; then
            echo "::error::Rollback tag is required for rollback action."
            exit 1
          fi
          echo "Initiating rollback on $HOST to tag: $ROLLBACK_TAG"
          $SSH_COMMAND "cd $TARGET_DIR && ./deploy.sh $TARGET_DIR $ROLLBACK_TAG rollback"
        else
          echo "::error::Invalid action specified: $ACTION"
          exit 1
        fi
